### ISSUE TITLE
Wrong format in constructor

### ISSUE THREAD

**Issue by WimWidgets** [laraning/nova-time-field#10]
Time data in my (MySQL) database is saved in `H:i:s` format. The time field tries to reconstitute the value by using `H:i`. This throws an `InvalidArgumentException`:
```
/vendor/laraning/nova-time-field/src/TimeField.php(31): Carbon\\Carbon::createFromFormat('H:i', 'xx:xx:xx')
```
So as far as I can tell, the following line...
https://github.com/laraning/nova-time-field/blob/cb1fb71acfbdd8fd74183d4bbde07c11108d730f/src/TimeField.php#L31
...sould be:
```php
return Carbon::createFromFormat('H:i:s', $value)->format('H:i'); 
```
Another option would be to make both in the input and output formats configurable.

**Comment by laraning** [comment]
Thanks!

As soon as I get back from Laracon EU will check it out.
