### ISSUE TITLE
12 Hour Format in Update Form

### ISSUE THREAD

**Issue by tylernathanreed** [laraning/nova-time-field#27]
I'm trying to make the 12 hour format appear consistent across the UI.

I've created a datetime column on a table that I'm managing the time portion of that field using this package.

Here's the magic accessor on the model that I created to yield just the time portion:

```
/**
 * Creates the $this->start_time attribute for the Nova framework.
 *
 * @return \Carbon\Carbon|null
 */
public function getStartTimeAttribute()
{
    return !is_null($this->starts_at) ? carbon($this->starts_at)->format('H:i:s') : null;
}
```

And here's the field declaration in my resource:

```
TimeField::make('Start Time', 'start_time', function($value, $resource) {
    return Carbon::createFromFormat('H:i:s', $value)->format('g:i A');
})->withTwelveHourTime(),
```

On the Index, Detail, and Create pages, this value appears correctly (in the HH:MM AM/PM) format. However, on the Update page, the AM/PM information gets lost (i.e. 1:30 PM becomes 1:30 AM).

I would like the 12 hour format to show as 12 hours on the Update form as well (and not 13:30 instead of 1:30 PM).

Is there a feature that I'm missing, or this a bug with the package?

Based on some initial research, it looks like this package is assuming a 24 hour date format regardless of the 12 hour time preference. I believe all that needs to be done here is to conditionally change the [dateFormat](https://flatpickr.js.org/formatting/#time-formatting-tokens) option into flatpickr.

**Comment by brunocfalcao** [comment]
Sorry for the delay, going to analyse it and come back to you.

**Comment by brunocfalcao** [comment]
It was closed with the PR
