### ISSUE TITLE
Data Missing error

### ISSUE THREAD

**Issue by njsoria** [laraning/nova-time-field#30]
After upgrading to Laravel Nova 2.9.2 and Laravel 6.x I am not getting a Data Missing error when using this plugin. I was only storing the database with time as HH:mm:ss and now I can't convert back to DateTime.

Is there some modification I need to make to this package?

`Message
Data missing
Level
ERROR
UserId
1
Exception
{
    "class": "InvalidArgumentException",
    "message": "Data missing",
    "code": 0,
    "file": "/home/vagrant/code/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:581",
    "trace": [
        "/home/vagrant/code/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:603",
        "/home/vagrant/code/vendor/laraning/nova-time-field/src/TimeField.php:32",
        "/home/vagrant/code/nova/src/Fields/Field.php:242",`

**Comment by yatsyukv** [comment]
@njsoria 
That's Carbon throwing it, as it can't parse `null`. 
The workaround solution is to set the default value for your `time` (or whatever you use) model attribute.

```php
    protected $attributes = [
        'time' => '00:00:00'
    ];
```

**Comment by njsoria** [comment]
Thanks! This seems to have resolved it. I had to update the database to eliminate the existing NULL values and replace with the default.

**Comment by laraning** [comment]
Yes but still the field constructor shouldn't return an error.

I've added a ternary operator to resolve it and to result 'empty' in case of a null.

Thanks @njsoria and @yatsyukv !

**Comment by njsoria** [comment]
Thanks !! Keeps the project sharp !
