### ISSUE TITLE
Unable to type a time into the field

### ISSUE THREAD

**Issue by ragingdave** [laraning/nova-time-field#35]
When using this field, it seems that although the field is editable, it has no effect and is basically a readonly field from manual entry. Even if you type in the field, it is overwritten once the time picker closes with the default 12:00AM.

**Comment by laraning** [comment]
Hi, sorry for the delay, did you try the latest version? Does it still happen?

If affirmative, then will ask you if you can give me a clear step-by-step example so I can test.

Thanks!

**Comment by hardiksinh** [comment]
Yes, I am facing same issue. Also, once clicked in input, it can not clear out. It is always 12:00 AM.

**Comment by laraning** [comment]
Ok, great ! Let me know if you find something not working. Closing it then.
