### ISSUE TITLE
Nullable does not work.

### ISSUE THREAD

**Issue by philipbaginski** [laraning/nova-time-field#37]
Hi! There is no option to provide empty value. Every time I make field valueless, it is saved with value: 12:00:00

I run last version. Any help?

**Comment by PrzemekTkaczyk** [comment]
same for me :(

**Comment by PrzemekTkaczyk** [comment]
@philipbaginski 
On new version sth like this works:
 ```TimeField::make('time)->nullable()```

**Comment by laraning** [comment]
Yeap, will write it out soon. The thing is yuo need to have the rules nullable to allow the nullable value to be accepted. Will make some tests still, thanks!

**Comment by laraning** [comment]
Corrected in the next release.
