### ISSUE TITLE
Validation message showing twice

### ISSUE THREAD

**Issue by hardiksinh** [laraning/nova-time-field#38]
Validation message is showing twice when using required rule.

Using only one field:

`TimeField::make(__('Working Hours From'))->withTwelveHourTime()->sortable()->rules('required')`

![Screenshot_2020-05-09 admin-single time field](https://user-images.githubusercontent.com/1895099/81438726-d7c8d900-918a-11ea-98e2-59d656590e98.png)

Using two fields:

`TimeField::make(__('Working Hours From'))->withTwelveHourTime()->sortable()->rules('required'),`
`TimeField::make(__('Working Hours To'))->withTwelveHourTime()->sortable()->rules('required')`

![Screenshot_2020-05-09 admin](https://user-images.githubusercontent.com/1895099/81438765-ec0cd600-918a-11ea-85c2-1cd7f922dc71.png)

Version: 0.2.5

**Comment by laraning** [comment]
Corrected in the next version, thanks!
