### ISSUE TITLE
Nova 2.0 support

### ISSUE THREAD

**Issue by markwalet** [laraning/nova-time-field#4]
I just installed the package in a fresh Nova 2.0 installation and the styling is off. The error messages do not look the same anymore.

There are also some functional problems. But someone already made a pr for that: #3

**Comment by ragingdave** [comment]
Any update on this? Nova 2.0 has already been out for nearly a month and this package is still incompatible even though there are a few (albeit a little duplicated) PRs to address the issues.

**Comment by christianmarth** [comment]
@markwalet can you please just merge the PR please

**Comment by markwalet** [comment]
Why should I merge? This is not my project

**Comment by charlielangridge** [comment]
@laraning can you merge this PR please!!

**Comment by jhm-ciberman** [comment]
@laraning, If you are not going to maintain this amazing package anymore, can you please add another admin to the repo so the comunity can mantain this package?

**Comment by laraning** [comment]
Hi guys,

Sorry, just wake up from the dead.

Let me check all PR's tomorrow and let's make some action here.

Sorry once again. Will be back asap.
