### ISSUE TITLE
Error when field is casted as datetime

### ISSUE THREAD

**Issue by salmanhijazi** [laraning/nova-time-field#40]
Hello,

Laravel only allows to cast time as datetime, which means that when a set my column name in the casted array, nova-time-field throws an error as it expects a certain format. Is it possible to change 

`Carbon::createFromFormat('H:i:s', $value)`

to

`Carbon::parse($value)`

in TimeField.php?

Cheers

**Comment by laraning** [comment]
Thanks, will check it out 👍

**Comment by salmanhijazi** [comment]
Thank you! Solved this for now by sending a callback function:

```
TimeField::make('Time', 'time', function ($value) {
    return $value === null ? '' : Carbon::parse($value)->format('g:i A');
})
```

**Comment by brunocfalcao** [comment]
Does this still occurs on this latest version? Is it possible to check it out? Thanks
