### ISSUE TITLE
Remove leading 0 when displaying withTwelveHourTime()

### ISSUE THREAD

**Issue by drewroberts** [laraning/nova-time-field#46]
I'm using this code to display the time in a Nova index:

`
TimeField::make('Time')->withTwelveHourTime(),
`

It displays a leading 0 and it would be helpful to have that removed. Here is a screenshot:

<img width="160" alt="Screen Shot 2020-10-21 at 10 21 50 AM" src="https://user-images.githubusercontent.com/24581081/96733315-47bccb80-1387-11eb-8b77-edfe6be8cfcb.png">

**Comment by laraning** [comment]
corrected, thanks. Will be released in the next version
