### ISSUE TITLE
Javascript error in v1.1

### ISSUE THREAD

**Issue by jkudish** [laraning/nova-time-field#51]
I'm consistently getting the following javascript error with v1.1:

![image](https://user-images.githubusercontent.com/260253/99726343-3d1b5200-2a6b-11eb-82ef-ccd082519406.png)

The error prevents the field from saving its value. Reverting to v1.0 fixes the problem.

My fields are defined very simply:

```php
TimeField::make(__('Start Time'), 'start_time')
                ->rules(['required', 'before:end_time']),

TimeField::make(__('End Time'), 'end_time')
                ->rules(['required', 'after:start_time']),
```

Let me know if I can provide any additional info

**Comment by brunocfalcao** [comment]
Hi, made a new tagged version that should resolve your issue, thanks for reporting

**Comment by jkudish** [comment]
Thanks for the update, it works!
