### ISSUE TITLE
Using ->rules makes the Field disappear

### ISSUE THREAD

**Issue by dajoeberlei** [laraning/nova-time-field#9]
Hello,

i'm using Laravel Nova 2.0.5 and i just started using TimeField.
I wanted to add
"->rules('required')" to my TimeField but if i do the Field just disappears in the Nova Backend.

**Comment by laraning** [comment]
Thanks, will check it out. Sorry for th delay

**Comment by laraning** [comment]
Just released a new version, can you check?
